### ISSUE TITLE
I get "undefined is not a function" with a fresh installation

### ISSUE THREAD

**Issue by michas79** [ghurlman/torii-azure-provider#1]
With a fresh installation of node (v0.12.1), npm (2.5.1) and bower (1.3.12) I try to use this addon. I follow your installation steps but if I start ember server I only get this error:

 undefined is not a function
TypeError: undefined is not a function
    at EmberCLIDependencyChecker.readBowerDependencies (D:\workspace\TodoApp\client\node_modules\ember-cli-torii-azure-provider\node_modules\ember-cli-dependency-checker\lib\dependency-checker.js:80:35)
    at EmberCLIDependencyChecker.checkDependencies (D:\workspace\TodoApp\client\node_modules\ember-cli-torii-azure-provider\node_modules\ember-cli-dependency-checker\lib\dependency-checker.js:28:24)
    at new EmberCLIDependencyChecker (D:\workspace\TodoApp\client\node_modules\ember-cli-torii-azure-provider\node_modules\ember-cli-dependency-checker\lib\dependency-checker.js:19:8)
    at D:\workspace\TodoApp\client\node_modules\ember-cli\lib\models\addons-factory.js:44:19
    at visit (D:\workspace\TodoApp\client\node_modules\ember-cli\lib\utilities\DAG.js:23:3)
    at DAG.topsort (D:\workspace\TodoApp\client\node_modules\ember-cli\lib\utilities\DAG.js:82:7)
    at AddonsFactory.initializeAddons (D:\workspace\TodoApp\client\node_modules\ember-cli\lib\models\addons-factory.js:40:9)
    at Class.Addon.initializeAddons (D:\workspace\TodoApp\client\node_modules\ember-cli\lib\models\addon.js:189:36)
    at setupRegistryForEachAddon (D:\workspace\TodoApp\client\node_modules\ember-cli\lib\preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (D:\workspace\TodoApp\client\node_modules\ember-cli\lib\preprocessors.js:46:3)

**Comment by ghurlman** [comment]
Able to repro on a fresh install of NPM/CLI/bower - will dig into this, I suspect a different CLI version on my original dev box, but can't confirm until tonight.

**Comment by ghurlman** [comment]
Updated dependencies and install instructions; should be good to go now.

**Comment by ghurlman** [comment]
Updated dependencies and install instructions; should be good to go now.
